### ISSUE TITLE
socket handler blocking call -> subscribe

### ISSUE THREAD

**Issue by Ben-Mark** [monkey-codes/java-reactive-chat#3]
Hey monkey-codes,
you're calling subscribe in a non-blocking code..

please fix it

**Comment by monkey-codes** [comment]
Hi,
Thanks for feedback. 

Do you have some sample code or suggestion on how to do that? Or are you simply suggesting using something like [subscribeOn](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#subscribeOn-reactor.core.scheduler.Scheduler-)

**Comment by zinoviy23** [comment]
You can use then method,
looks like 
```java
return session.receive()
                .map(WebSocketMessage::getPayloadAsText)
                .map(this::toEvent)
                .doOnNext(subscriber::onNext)
                .doOnError(subscriber::onError)
                .doOnComplete(subscriber::onComplete)
                .then(session.send(outputEvents.map(session::textMessage)));
```

**Comment by monkey-codes** [comment]
@zinoviy23 Thanks for the feedback, I've updated the code https://github.com/monkey-codes/java-reactive-chat/commit/40982ca4e093540858bf1701406899d36afb5f95

**Comment by monkey-codes** [comment]
Fixed
